In [ ]:
#first lab

In [1]:
x=8
print(f"this a value of a number : {x}")

this a value of a number : 8


In [3]:
x=6
print(f"{x}__{x*2}__{x*4}__{x*6}")

6__12__24__36


In [5]:
input("What's up")

What's up hii


'hii'

In [7]:
ver=int(input("enter a number"))

enter a number 66


In [ ]:
#lists Day 3

In [9]:
list=["rohail","ahrar","yaseen","wasim"]
print(list)

['rohail', 'ahrar', 'yaseen', 'wasim']


In [11]:
int1 = int(input("enter obt marks:"))
int2  = int (input("enter total marks"))
percentage = int1/int2*100
print("you scored :",percentage)

enter obt marks: 55
enter total marks 100


you scored : 55.00000000000001


In [ ]:
#day 4

In [17]:
my_list = [3,4,5]
my_list.pop( 2)

5

In [21]:
# Define a list
my_list = [1, 2, 3, 4, 5]

# Remove a specific element (e.g., 3)
my_list.remove(3)

print("List after removing 3:", my_list)


List after removing 3: [1, 2, 4, 5]


In [ ]:
#Continue and Break statement 6th August

In [13]:
for i in range(10):
   if i==5:
       print(i)
       continue
   else:
       print(i)

0
1
2
3
4
5
6
7
8
9


In [15]:
for i in range(10):
   if i==5:
       print(i)
       break
   else:
       print(i)

0
1
2
3
4
5


<!-- 7th August Labs -->


In [ ]:
# 7th AUgust Labs



In [15]:
def display_message(top,set):
    print(f"today's Topic is(top)")
    print(f"{set}")
    
display_message("function","Today we learnt about python")
    

today's Topic is(top)
Today we learnt about python


In [41]:
def fav_book(fvrt):
    print(f"my favourite book is {fvrt} Written By Napoleon Hill")
fav_book("(Think and Grow Rich)")


my favourite book is (Think and Grow Rich) Written By Napoleon Hill


In [37]:
def describe_cars(name , model):
    print(f"i have a {name} of {model} model")
    print(f" {model} model")
describe_cars("farari", "2001")

i have a farari of 2001 model


In [82]:
x = int(input("size of your shirt:"))
def make_shrt(size):
    if size <=12:
        print(f"your shirt size is small and your size {size} ")
    elif size <=15:
        print(f"your shirt size is medium and your size{size} ")
    elif size <=20:
        print(f"your shirt size is large and your size{size} ")
    else:
        print(f" your shirt size is extra large and your size:{size}   \n") 
   
  
    return size
make_shrt(x)


size of your shirt: 44


 your shirt size is extra large and your size:44   



44

In [3]:
# 8 August to 11th august Labs


In [7]:
 # import only sin and pi from maths module:
from math import sin,pi
print (math.sin(3.14))
print(pi) 

0.0015926529164868282
3.141592653589793


In [15]:
from math import sin,pi
print(math.sin(90))
print(sin)

0.8939966636005579
<built-in function sin>


In [3]:
import math
math.ceil(3.14)

4

In [25]:
import random
random.randint(1,20)


18

In [27]:
import random
random.uniform(1,20)

4.869995347694625

In [31]:
random.choice([1,"up","down",2,3,5,6])

3

In [34]:
import math
8**2

64

In [49]:
math.pow(4,3)     

64.0

In [53]:
53==106/2

True

In [55]:
53==104/2

False

In [57]:
math.pi

3.141592653589793

In [59]:
  math.sqrt(math.pi)       #formula for square root

1.7724538509055159

In [63]:
math.dist([3],[6])         #formula for distance

3.0

In [65]:
math.dist([-3],[-6])  #arrangement dosen't matter, we can change sequence like we can write -6 first

3.0

In [67]:
math.ceil(3.14157)

4

In [1]:
# 12th august labs
#Class


In [1]:
class BankAccount:
.    def __init__(self, owner, balance=0):
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        print("Amount Deposited: ", amount)
        self.balance += amount
        print("Total Balance: ", self.balance)

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient Balance")
        else:
            self.balance = self.balance - amount
            print(f"{amount} is withdrawn")

    def get_balance(self):
        return self.balance
obj1 = BankAccount("ABC", 1300)
obj1.deposit(9000)
print("Current Balance: ", obj1.get_balance())
obj1.withdraw(5000)
print("Current Balance: ", obj1.get_balance())


Amount Deposited:  9000
Total Balance:  10300
Current Balance:  10300
5000 is withdrawn
Current Balance:  5300


In [ ]:

# Python Class Example: Managing Employee Information with Methods for Full Name, Email, Salary, and Department


In [1]:
class employInformation():
    def __init__(self,fname,sname,salary,department):
        self.fname=fname
        self.sname=sname
        self.salary=salary
        self.department=department
    def fullName(self):
        print(f'Full name: {self.fname+" "+self.sname}')
    def email(self):
        print(f'Email: {self.fname+self.sname+"0786@gmail.com"}')
    def employ_department(self):
        print(f'Department: {self.department}')
    def employ_salary(self):
        print(f'Salary:',self.salary)
obj=employInformation('Waseem','waso',30000,' Management')
obj.fullName()
obj.email()
obj.employ_salary()
obj.employ_department()

Full name: Waseem waso
Email: Waseemwaso0786@gmail.com
Salary: 30000
Department:  Management


In [4]:
list = [1 , 4 ,5]
list2 = [2 , 5 ,6]
list4 = list[2] + list[0]
list4

6

In [20]:
import numpy as np
list = np.array([2 , 5 ,6 ,66 , 65 , 76])
index = np.array([2 , 3])
list_4 = np.arange(8)
list_5= np.shape(list)
list[index]
list_5

(6,)

In [20]:
import numpy as np
list = np.array([2 , 5 ,6 ,66 , 65 , 76])
index = np.array([2 , 3])
list_4 = np.arange(8)
list_5= np.shape(list)
list[index]
list_5

(6,)

In [20]:
import numpy as np
list = np.array([2 , 5 ,6 ,66 , 65 , 76])
index = np.array([2 , 3])
list_4 = np.arange(8)
list_5= np.shape(list)
list[index]
list_5

(6,)

In [17]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.ones((2 , 3 ,3, 4))
print(d)


[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [21]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.ones((2 , 3 ,3, 4))
d.ndim                                                 #find dimensions



4

In [23]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.ones((2 , 3 ,3, 4))                                    #find size 
d.size


72

In [25]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.ones((2 , 3 ,3))
d.ndim


3

In [27]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((2 , 3 ,3, 4))
print(d) 


[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [29]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((2 , 3 ,3, 4))
d.size


72

In [31]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((2 , 3 ,3, 4))
d.ndim


4

In [33]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((2 , 3 ,3, 4))
d.ndim
d


array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [35]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((10,50,10))
print(d)


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
